"use strict";
let state = null;
const $ = id => document.getElementById(id);
const ORIGINS = ["gulf", "west_africa"];
const roundHints = {1:"表达你的初始判断。",2:"你已经看到上一轮其它公司的公开意向，现在可以修正。",3:"最后一次同时提交；结算后直接 Firm，没有第四轮反悔。"};

function fmtM(v){ if(v==null) return "—"; return `${(v/1e6).toFixed(2)}m`; }
function fmtMoney(v){ if(v==null) return "—"; if(Math.abs(v)>=1e9) return `$${(v/1e9).toFixed(2)}bn`; if(Math.abs(v)>=1e6) return `$${(v/1e6).toFixed(2)}m`; return `$${Math.round(v).toLocaleString()}`; }
function fmtTce(v){ return v==null ? "—" : `$${Math.round(v).toLocaleString()}`; }
function show(id, yes=true){ $(id).classList.toggle("hidden", !yes); }
function toast(msg, error=false){ const t=$("toast"); t.textContent=msg; t.classList.toggle("error",error); show("toast",true); clearTimeout(toast.timer); toast.timer=setTimeout(()=>show("toast",false),2600); }
async function api(path, body){ const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); const data=await r.json(); if(!r.ok||data.ok===false) throw new Error(data.error||`HTTP ${r.status}`); return data; }

function render(){ if(!state) return; $("seedLabel").textContent=`Seed ${state.seed}`; $("dateLabel").textContent=state.date?.label||"2030–2039"; $("turnLabel").textContent=`Turn ${Math.min(state.turn+1,state.total_turns)} / ${state.total_turns}`;
  show("setupPanel", state.phase==="choose_company" && !state.candidates?.length); show("candidatePanel", state.phase==="choose_company" && state.candidates?.length); show("gamePanel", ["round","turn_complete","game_over"].includes(state.phase)); show("turnCompletePanel", state.phase==="turn_complete"); show("gameOverPanel", state.phase==="game_over");
  if(state.phase==="choose_company") renderCandidates();
  if(state.human) renderGame();
}

function renderCandidates(){ const grid=$("candidateGrid"); grid.innerHTML=""; state.candidates.forEach(c=>{ const el=document.createElement("article"); el.className="candidate card"; const st=c.status||{}; el.innerHTML=`<div class="eyebrow">${c.policy}</div><h3>${c.name}</h3><p>每家公司都是 ${c.fleet_total} 艘同规模资产；差别来自 warm start 后的真实位置。</p><div class="candidate-stats"><div><span>Gulf prompt</span><b>${st["prompt:gulf"]||0}</b></div><div><span>WAF prompt</span><b>${st["prompt:west_africa"]||0}</b></div><div><span>Laden</span><b>${st.laden||0}</b></div><div><span>Ballast</span><b>${st.ballast||0}</b></div></div><button class="primary">接手 ${c.name}</button>`; el.querySelector("button").onclick=()=>chooseCompany(c.company_id); grid.appendChild(el); }); }

function routeRender(origin,prefix){ const r=state.market.routes[origin], s=state.market.seller_offers[origin]; $(`${prefix}Tce`).textContent=fmtTce(r.benchmark_real_tce); $(`${prefix}Cargo`).textContent=fmtM(r.cargo_bbl); $(`${prefix}Offer`).textContent=fmtM(s.final_offer_bbl); $(`${prefix}Queue`).textContent=`${r.queue_ship_count} ships`; $(`${prefix}Marginal`).textContent=r.marginal_ship_id?`#${r.marginal_ship_id} · ${Math.round((r.marginal_load_factor||0)*100)}%`:"none"; const ev=r.capacity_evidence||{}; $(`${prefix}Capacity`).innerHTML=["trial","reserve","proposed","committed"].map(k=>`<span>${k} ${ev[k]?.ship_count||0}</span>`).join(""); const own=state.human?.market_positions?.[origin]; $(`${prefix}Own`).innerHTML=own?`你的船：<b>${own.offered}</b> offered · ${own.full} full · ${own.marginal} marginal · ${own.unused} unused`:"你的船：—"; }
function renderInventory(){ const d=state.market.destination_inventory, open=d.opening, rows=[{turn:"NOW",stock_bbl:open.stock_bbl,soft_pressure:open.soft_pressure},...d.future_path]; $("inventorySignal").textContent=`signal ${open.soft_pressure>=0?"+":""}${open.soft_pressure.toFixed(2)}`; $("inventoryTimeline").innerHTML=rows.map((r,i)=>`<div class="tick ${r.soft_pressure<-.3?"low":r.soft_pressure>.3?"high":""}"><span>${i?`t+${i}`:"NOW"}</span><strong>${fmtM(r.stock_bbl)}</strong><span>soft ${r.soft_pressure>=0?"+":""}${r.soft_pressure.toFixed(2)}</span></div>`).join(""); }
function renderFleet(){ const f=state.human.fleet; $("fleetTotal").textContent=`${f.total} ships`; $("fleetStatus").innerHTML=Object.entries(f.status).map(([k,v])=>`<span>${k} <b>${v}</b></span>`).join(""); const e=state.human.eligible, a=state.human.current_action; $("offerGulfMax").textContent=`/ ${e.prompt_counts.gulf}`; $("offerWafMax").textContent=`/ ${e.prompt_counts.west_africa}`; $("offerGulf").max=e.prompt_counts.gulf; $("offerWaf").max=e.prompt_counts.west_africa; $("offerGulf").value=a?.offer_counts.gulf??e.prompt_counts.gulf; $("offerWaf").value=a?.offer_counts.west_africa??e.prompt_counts.west_africa; $("ballastGulf").value=a?.ballast_counts.gulf??0; $("ballastWaf").value=a?.ballast_counts.west_africa??0; $("eaIdleHelp").textContent=`East Asia 当前有 ${e.east_asia_idle_count} 条本公司空船。剩余空船保持等待；改投只影响 future tonnage。`; }
function renderAdvisor(){ const a=state.human.advisor; if(!a){$("advisorSuggestion").textContent="本回合已结算";$("advisorReasons").innerHTML="";return;} const s=a.suggested_action; $("advisorSuggestion").textContent=`Prompt: Gulf ${s.offer_counts.gulf} / WAF ${s.offer_counts.west_africa} · Ballast: Gulf ${s.ballast_counts.gulf} / WAF ${s.ballast_counts.west_africa}`; $("advisorReasons").innerHTML=a.reasons.map(x=>`<li>${x}</li>`).join(""); $("advisorRisk").textContent=a.risk; }
function renderLeaderboard(){ const h=state.human_company_id; $("leaderboard").innerHTML=state.leaderboard.map(r=>`<div class="leader-row ${r.company_id===h?"you":""}"><span>#${r.rank}</span><b>${r.name}</b><em>${fmtMoney(r.gross_service_value_real_usd)}</em></div>`).join(""); }
function renderTape(){ const rounds=state.current_rounds||[], rows=state.history_tail||[]; const live=rounds.slice().reverse().map(r=>`<div class="tape-item"><span>本回合 R${r.round} ${r.round_name}</span><strong>G ${fmtTce(r.routes.gulf.benchmark_real_tce)}</strong><strong>W ${fmtTce(r.routes.west_africa.benchmark_real_tce)}</strong></div>`).join(""); const hist=rows.slice().reverse().map(r=>{const g=r.final_market.routes.gulf,w=r.final_market.routes.west_africa;return `<div class="tape-item"><span>${r.year}-${String(r.month).padStart(2,"0")} T${r.turn_in_month}</span><strong>G ${fmtTce(g.benchmark_real_tce)}</strong><strong>W ${fmtTce(w.benchmark_real_tce)}</strong></div>`}).join(""); $("marketTape").innerHTML=live+hist||"<span class=\"micro\">十年历史将从这里开始积累。</span>"; }
function renderGame(){ $("humanCompanyName").textContent=state.human.company.name; $("roundBadge").textContent=state.round?`R${state.round}`:"SET"; $("roundName").textContent=state.round_name||"Turn settled"; $("roundHint").textContent=state.round?roundHints[state.round]:"真实船位、在途货物和库存已经推进 10 个运营日。"; if(state.market){routeRender("gulf","gulf");routeRender("west_africa","waf");renderInventory();} renderFleet();renderAdvisor();renderLeaderboard();renderTape(); const active=state.phase==="round"; ["advisorButton","keepButton","submitButton","offerGulf","offerWaf","ballastGulf","ballastWaf"].forEach(id=>$(id).disabled=!active); if(state.phase==="turn_complete"&&state.human.last_turn_result){const r=state.human.last_turn_result;$("turnResultText").textContent=`本公司装载 ${fmtM(r.cargo_bbl)}，本回合 Gross Service Value ${fmtMoney(r.gross_service_value_real_usd)}；ballast ${r.ballasts} 艘。`;} }

function actionFromInputs(){ const e=state.human.eligible; const og=Number($("offerGulf").value),ow=Number($("offerWaf").value),bg=Number($("ballastGulf").value),bw=Number($("ballastWaf").value); for(const [v,max,label] of [[og,e.prompt_counts.gulf,"Gulf prompt"],[ow,e.prompt_counts.west_africa,"WAF prompt"]]) if(!Number.isInteger(v)||v<0||v>max) throw new Error(`${label} 数量无效`); if(![bg,bw].every(Number.isInteger)||bg<0||bw<0||bg+bw>e.east_asia_idle_count) throw new Error("East Asia ballast 数量超过可用空船"); return {offer_counts:{gulf:og,west_africa:ow},ballast_counts:{gulf:bg,west_africa:bw}}; }
async function newGame(){ const b=$("newGameButton"),old=b.textContent; try{b.disabled=true;b.textContent="正在生成世界…";const seed=Number($("seedInput").value); state=await api("/api/game/new",{seed}); show("setupPanel",false);render();}catch(e){toast(e.message,true);}finally{b.disabled=false;b.textContent=old;} }
async function chooseCompany(id){try{state=await api("/api/game/choose",{game_id:state.game_id,company_id:id});render();}catch(e){toast(e.message,true);} }
async function submit(opts={}){try{const body={game_id:state.game_id,round_token:state.round_token,...opts}; if(!opts.use_advisor&&!opts.keep) body.action=actionFromInputs(); state=await api("/api/game/round",body);render();}catch(e){toast(e.message,true);} }
async function nextTurn(){try{state=await api("/api/game/next",{game_id:state.game_id,round_token:state.round_token});render();}catch(e){toast(e.message,true);} }
async function saveGame(){try{const r=await fetch(`/api/game/save?game_id=${encodeURIComponent(state.game_id)}`),data=await r.json(); if(!r.ok) throw new Error(data.error); const blob=new Blob([JSON.stringify(data.checkpoint,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`main-6Clite-seed${state.seed}-turn${state.turn}.json`;a.click();URL.revokeObjectURL(url);}catch(e){toast(e.message,true);} }
async function loadFile(file){try{const checkpoint=JSON.parse(await file.text());state=await api("/api/game/load",{checkpoint});render();toast("存档已恢复");}catch(e){toast(e.message,true);} }

$("newGameButton").onclick=newGame; $("advisorButton").onclick=()=>submit({use_advisor:true}); $("keepButton").onclick=()=>submit({keep:true}); $("submitButton").onclick=()=>submit(); $("nextTurnButton").onclick=nextTurn; $("saveButton").onclick=saveGame; $("gameOverSave").onclick=saveGame; $("loadInput").onchange=e=>e.target.files[0]&&loadFile(e.target.files[0]);
render();
